### ISSUE TITLE
Observations regarding "ReproIn compatibility"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/example-dicom-structural#1]
Just here to collect notes (WiP) from trying heudiconv with -f reproin. WiP. Might of interest for @jbpoline from Berkeley (as github says) ;-)

## ImageType and Derived
These sequences have 
```
(0008,0008) CS [DERIVED\SECONDARY]                      #  18, 2 ImageType
```
unlike the ones I had to deal with, e.g.
```
(0008,0008) CS [ORIGINAL\PRIMARY\M\ND\NORM\FM\FIL]      #  34, 7 ImageType
```
which
1. have 3rd value providing information about the type of image (`M` for magnitude). 
 *Resolution*: Will fixup reproin heuristic to not rely/use if not available
2. are not derived. ATM we just ignored nearly all derived and kept only motion corrected one (if provided) for which we added `_acq-moco`.   *Resolution*:  TODO

## Subject ID

Here it is just empty:
```
$> dcmdump structural/dicoms/N2D_0001.dcm | grep -i -e 'Patient\(Name\|Id\)'
(0010,0010) PN (no value available)                     #   0, 0 PatientName
(0010,0020) LO (no value available)                     #   0, 0 PatientID
(0010,1000) LO (no value available)                     #   0, 0 RETIRED_OtherPatientIDs
```
- heudiconv 
  - we can provide sid in cmdline manually
  - I think I will for now disallow empty sid (since determines paths within .heudiconv/), but the whole sid handling might need to be RFed a bit anyways to allow for lookup based on other information (accession/time/...). TODO: issue within heudiconv

## ProtocolName vs SeriesDescription

Apparently in our Siemens data we had those identical (yet to check if that is consistent across):
```shell
$> dcmdump ~/picts/mris/dartmouth-phantoms/bids_test4-20161014/phantom-1/anat-T1w/1.3.12.2.1107.5.2.43.66112.2016101409261110045101885.dcm | grep -i -e 'anat-'          
(0008,103e) LO [anat-T1w]                               #   8, 1 SeriesDescription
(0018,1030) LO [anat-T1w]                               #   8, 1 ProtocolName
```
and we used ProtocolName (not SeriesDescription) to decide the destiny of the sequence. In this data `ProtocolName` is not provided and `SeriesDescription` is
```
$> dcmdump structural/dicoms/N2D_0001.dcm | grep -i -e '\(Series\(Number\|Description\)\|ProtocolName\)'
(0008,103e) LO [anat-T1w]                               #   8, 1 SeriesDescription
(0018,1030) LO (no value available)                     #   0, 0 ProtocolName
(0020,0011) IS [401]                                    #   4, 1 SeriesNumber
```
Here is a full list of those across all DICOMs I found at ///dicoms: http://www.onerussian.com/tmp/series-vs-protocol_name.txt (generated using `find -type d | grep -v "\.git" | while read d; do f=$(file -L $d/* 2>/dev/null | sed -ne "/DICOM/s,: DICOM.*,,pg" | head -n 1); [ -z "$f" ] || { out=$(dcmdump --read-file-only  "$f" 2>/dev/null |grep -e "\( Manufa\|SeriesDescription\|ProtocolName\)"); [ ! -z "$out" ] || continue; echo $d; echo $out | sed -e "s,^,  ,g"; }; done`

## ContentTime + ContentDate

Were missing here ((0008,0023) and (0008,0033)).  We extract them to place into _scans file.  Resolution (ReproIn): I will make them optional (with a warning)

**Comment by jbpoline** [comment]
:) thanks - will also play with it - and technically, I still have an appointment at Berkeley :)

**Comment by mih** [comment]
I have pushed an update that hopefully addresses the issues in full. I also documented the command used to alter the header fields in the README https://github.com/datalad/example-dicom-structural/blob/master/README.md

If this new version works for you, I will squash all commits to keep the repo size minimal.

**Comment by yarikoptic** [comment]
Cool, thanks, I will check it out. Did .git/objects grow notably with the changes? Didn't check recently how will git deals with binary blobs, may be it is not that bad

**Comment by mih** [comment]
FTR: Ran the current state through `heudiconv -f reproin`

```
% heudiconv -f reproin --files dicoms
INFO: Running heudiconv version 0.5
INFO: Analyzing 384 dicoms
INFO: Filtering out 0 dicoms based on their filename
INFO: Generated sequence info for 1 studies with 1 entries total
INFO: Processing sequence infos to deduce study/session
INFO: Study session for {'locator': 'Hanke/Stadler/0024_transrep', 'session': None, 'subject': 'sub02'}
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 'sub02', 'outdir': '/tmp/dicom_demo/structural/Hanke/Stadler/0024_transrep', 'session': None}
INFO: Processing 1 pre-sorted seqinfo entries
INFO: Processing 1 seqinfo entries
INFO: Skipped 1 sequences: ['401-anat-T1w']
INFO: Doing conversion using dcm2niix
INFO: PROCESSING DONE: {'subject': 'sub02', 'outdir': '/tmp/dicom_demo/structural/Hanke/Stadler/0024_transrep', 'session': None}
```

So there must be something missing still.

**Comment by jbpoline** [comment]
Same thing or similar here:

 heudiconv --file dicoms/ -f ~/code/repronim/heudiconv/heudiconv/heuristics/reproin.py -o test-convertion
INFO: Running heudiconv version 0.5.dev1
INFO: Analyzing 5460 dicoms
INFO: Filtering out 0 dicoms based on their filename
WARNING: dcmstack without support of pydicom >= 1.0 is detected. Adding a plug

INFO: Generated sequence info for 1 studies with 1 entries total
INFO: Processing sequence infos to deduce study/session
INFO: Study session for {'locator': 'Hanke/Stadler/0083_transrep2', 'subject': '', 'session': None}
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'outdir': '/home/jb/data/teaching/example-dicom-functional/test-convertion/Hanke/Stadler/0083_transrep2', 'session': None, 'subject': ''}
INFO: Processing 1 pre-sorted seqinfo entries
INFO: Processing 1 seqinfo entries
WARNING: Could not figure out where to stick 1 sequences: ['401-']
INFO: Doing conversion using dcm2niix
INFO: PROCESSING DONE: {'outdir': '/home/jb/data/teaching/example-dicom-functional/test-convertion/Hanke/Stadler/0083_transrep2', 'session': None, 'subject': ''}

**Comment by mih** [comment]
@yarikoptic @jbpoline 's report was on the functional dataset which still has my first attempt on the DICOM header settings

**Comment by jbpoline** [comment]
runs now fine with the dartmouth/enh-mih-... branch !

**Comment by mih** [comment]
DICOMs now have ContentDate and Time too.
